name: Hourly SF Weather Update

on:
  schedule:
    - cron: '0 8 * * *'  # Run every hour
  workflow_dispatch:      # Allow manual triggers

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install llm  # Assuming this is a custom package available via pip
        pip install pytz
        
    - name: Run weather script
      env:
        OPENAI_API_KEY: ${{ secrets.LLM_API_KEY }}  # For the LLM service
      run: python foggybot.py
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add weather_report.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update weather report [skip ci]" && git push)